version: '3'
services: 
  fastapi:
    hostname: fastapi
    container_name: fastapi
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app

  react:
    hostname: react
    container_name: react
    depends_on: 
      - fastapi
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"

  nginx:
    depends_on:
      - fastapi
      - react
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    hostname: nginx
    ports:
      - "80:80"
